image: node:9.9.0

cache:
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
    - CI=true npm run test -- --coverage
  coverage: /All files\s*\|\s*([\d\.]+)/

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - CI=true npm run build
    - rm -rf public/
    - mv build/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
