name: Release
"on":
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build and deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run ci:lint
      - name: Test
        run: npm run ci:test
      - name: Build
        run: npm run ci:build
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_STARDEW_VALLEY_PLANNER }}"
          channelId: live
          projectId: stardew-valley-planner
